### ISSUE TITLE
updated to xcode 7

### ISSUE THREAD

**Issue by moh1122** [alex-chan/AVCamSwift#10]
Hello
I updated to xcode 7 and im getting this error while building the project:
stringByAppendingPathComponent' is unavailable: Use stringByAppendingPathComponent on NSString instead.

any clue?
Thank you

**Comment by alex-chan** [comment]
It's swift's new  language feather. Just try its hint.

**Comment by Charles-Hsu** [comment]
Hi Alex,

Great Work!

But, I have one question:
Can AVCam record a movie playing by AVPlayer?

Thank you.

Charles

**Comment by alex-chan** [comment]
Sorry, I don't remember that...

2015-11-25 7:07 GMT+08:00 chiachi notifications@github.com:

**Comment by alex-chan** [comment]
Fix it
