### ISSUE TITLE
cannot read entitlement data error

### ISSUE THREAD

**Issue by Swiftology** [alex-chan/AVCamSwift#2]
I keep getting a cannot read entitlement data error when running AVCamSwift on my iPhone 5. Please check the image below for more details

![screen shot 2015-05-13 at 3 57 57 pm](https://cloud.githubusercontent.com/assets/12157619/7615475/62ae3114-f98d-11e4-85b2-d21265b365f6.png)

**Comment by alex-chan** [comment]
Oh, that's because I use it on a jailbreak device before. 
Now you can just checkout the latest  commit which I commited last day to fix this issue.
