### ISSUE TITLE
Swift 2.0, Xcode 7

### ISSUE THREAD

**Issue by ejpusa-zz** [alex-chan/AVCamSwift#3]
hi,

Will you be updating to Swift 2.0/Xcode 7 soon?  thanks

**Comment by alex-chan** [comment]
I will update it  when Xcode7 officially released

**Comment by ejpusa-zz** [comment]
Cool. If I wanted to jump into Swift 2.0/7 do you have a video framework u
would recommend now, may tackle it myself, just was checking to see if one
was already released. thanks, good job on this one.

What I noticed is that other repos (alamofire, etc), already have Swift 2.0
branch:

https://github.com/Alamofire/Alamofire/tree/swift-2.0
https://github.com/SwiftyJSON/SwiftyJSON/tree/xcode7

On Sun, Jun 14, 2015 at 9:36 AM, alex-chan notifications@github.com wrote:

> I will update it when Xcode7 officially released
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex-chan/AVCamSwift/issues/3#issuecomment-111827447.

## 

---

@ejpusa http://twitter.com/ejpusa

**Comment by alex-chan** [comment]
GPUImage is a good framework and easy  to use(I'm not sure it's updated for iOS 7, CoreImage has good performance but a bit harder to use. 
Nowadays, XCode 7 is still not officially released. You can try to rewrite it . I think it's quiet easy for you!

**Comment by alex-chan** [comment]
Update to swift2 compiled by xcode7 beta4.
