### ISSUE TITLE
uncaught exception 'NSRangeException' - Cannot remove an observer

### ISSUE THREAD

**Issue by mlejva** [alex-chan/AVCamSwift#4]
Hi,
whenever I dismiss view controller with camera I get this error:

```
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <App.CameraViewController 0x16ea7f70> for the key path "movieFileOutput.recording" from <App.CameraViewController 0x16ea7f70> because it is not registered as an observer.'
*** First throw call stack:
(0x2a9e6fef 0x3908ac8b 0x2a9e6f35 0x2b6850f5 0x2b684b07 0x2b6849ab 0xbeb40 0xbca88 0x85c173 0x864d67 0x85ea61 0x866b09 0x867e19 0x39782dc1 0x39782b14)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by alex-chan** [comment]
updated to swift2 compiled by xcode7 beta4. let me know you still encounter this problem

**Comment by mlejva** [comment]
I have figured out what is the problem.

You are registering this:
`self.addObserver(self, forKeyPath: "movieFileOutput.recording", options: NSKeyValueObservingOptions.Old | NSKeyValueObservingOptions.New, context: &RecordingContext)
`
But removing this:
`self.removeObserver(self, forKeyPath: "movieFileOutput.recording", context: &SessionRunningAndDeviceAuthorizedContext)`

Context in remove line is wrong and should be `&RecordingContext`

Can you please explain why are you removing observers in `dispatch_async` ?

**Comment by alex-chan** [comment]
Oh, that my mistake, thank you!. Maybe I just followed the related iOS version `dispatch_async`
