### ISSUE TITLE
AVCam Swift crashing on real device

### ISSUE THREAD

**Issue by moh1122** [alex-chan/AVCamSwift#5]
Hello alex
hope everything is ok thank you for this project its amazing and great.
Can you  help me with this crash I'm running your project on my real device but it crashes when the microphone is disabled. I really want to upgrade it with more features but can you tell me why is it crashing when the microphone is off. I want it to give an alert that states that the microphone is off, just like that cam.
Thank you
Awaiting your reply

**Comment by alex-chan** [comment]
Did you try it on Xcode7 ? in my testing . It works fine
