### ISSUE TITLE
avcam on xcode 6.4

### ISSUE THREAD

**Issue by moh1122** [alex-chan/AVCamSwift#6]
hello I'm running your AVCam swift project on Xcode 6.4 and it has 42 errors.
can you please help me in this your old version was working well with me but it crashes on the the real device when the microphone is turned off can you lead me to alert the users that the microphone need there permission in order to use the app.
Thank you

**Comment by alex-chan** [comment]
I just upgraded from xcode6.4 to xcode7beta4. xcode7  shipped with swift2. which contains a lot of exciting functions and syntax. I suggest you upgrade to it too. This code works fine on xcode7
